# Generated by Django 5.2.7 on 2025-10-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("Hard", "Hard"), ("Soft", "Soft")], default=None
            ),
        ),
    ]
